version: '3'

services:
  app:
    image: node:alpine
    working_dir: /app
    ports:
      - "3008:3008"
    volumes:
      - .:/app
    command: npm run dev
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: exemplo  
    ports:
      - "27020:27020"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local
